

services:
  amuda_lab_backend: 
    build: . 
    container_name: amuda_lab_backend 
    ports:
      - "5000:5000" 
    environment:
      MONGODB_URI: ${MONGODB_URI}
      # DB_NAME: ${DB_NAME}
      PORT: ${PORT:-5000} 
      SECRET_KEY: ${SECRET_KEY}
      EXPIRES_IN: ${EXPIRES_IN}
      MAIL_EXPIRES_IN: ${MAIL_EXPIRES_IN}
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      FORGOT_SECRET_KEY: ${FORGOT_SECRET_KEY}
      STATIC_URL: ${STATIC_URL}
      BREVO_USER: ${BREVO_USER}
      BREVO_PASS: ${BREVO_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
    restart: unless-stopped 

   

networks:
  default:
    driver: bridge

